DROP TABLE IF EXISTS gifs CASCADE;
DROP TABLE IF EXISTS favs CASCADE;

CREATE TABLE gifs(
  id SERIAL PRIMARY KEY,
  url VARCHAR(255)
);

CREATE TABLE favs(
  id SERIAL PRIMARY KEY,
  url VARCHAR(255),
  gifs_id SERIAL REFERENCES gifs(id)
);
